[build]
  base = "afyametrix"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]